export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID: 'MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID',
    START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
    RECIEVED_NOTIFICATIONS: 'RECIEVED_NOTIFICATIONS',
    FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST'
}